FROM python:3.11.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["sh", "-c", "if [ -f Data/data.csv ] && [ -f Data/node.csv ]; then python optimal_honeypot.py data.csv node.csv; else echo 'Error: place your data.csv and node.csv and mounted volume.'; fi"]